export const HOMEPAGE_LOAD_QUIZ_REQUEST = "HOMEPAGE_LOAD_QUIZ_REQUEST";
export const HOMEPAGE_LOAD_QUIZ_SUCCESS = "HOMEPAGE_LOAD_QUIZ_SUCCESS";
export const HOMEPAGE_LOAD_QUIZ_FAILED = "HOMEPAGE_LOAD_QUIZ_FAILED";

export const LOAD_QUIZ_REQUEST = "QUIZ_LOAD";
export const LOAD_QUIZ_SUCCESS = "LOAD_QUIZ_SUCCESS";
export const LOAD_QUIZ_FAILED = "LOAD_QUIZ_FAILED";