export const HOMEPAGE_LOAD_QUIZ_REQUEST = "HOMEPAGE_LOAD_QUIZ_REQUEST";
export const HOMEPAGE_LOAD_QUIZ_SUCCESS = "HOMEPAGE_LOAD_QUIZ_SUCCESS";
export const HOMEPAGE_LOAD_QUIZ_FAILED = "HOMEPAGE_LOAD_QUIZ_FAILED";

export const LOAD_QUIZ_REQUEST = "QUIZ_LOAD";
export const LOAD_QUIZ_SUCCESS = "LOAD_QUIZ_SUCCESS";
export const LOAD_QUIZ_FAILED = "LOAD_QUIZ_FAILED";


export const SCORE_CHANGE = "SCORE_CHANGE";
export const SET_SCORE_NULL = "SET_SCORE_NULL";
export const SET_QUIZ_TIMER = "SET_QUIZ_TIMER";
export const SELECT_ANSWER = "SELECT_ANSWER";

export const ADD_QUIZ_REQUEST = "ADD_QUIZ_REQUEST";
export const ADD_QUIZ_REQUEST_SUCCESS = "ADD_QUIZ_REQUEST_SUCCESS";
export const ADD_QUIZ_REQUEST_FAILED = "ADD_QUIZ_REQUEST_FAILED";