export const HOMEPAGE_LOAD_QUIZ_REQUEST = "HOMEPAGE_LOAD_QUIZ_REQUEST";
export const HOMEPAGE_LOAD_QUIZ_SUCCESS = "HOMEPAGE_LOAD_QUIZ_SUCCESS";
export const HOMEPAGE_LOAD_QUIZ_FAILED = "HOMEPAGE_LOAD_QUIZ_FAILED";