export const LEADERBOARD_REQUEST = "LEADERBOARD_REQUEST";
export const LEADERBOARD_REQUEST_SUCCESS = "LEADERBOARD_REQUEST_SUCCESS";
export const LEADERBOARD_REQUEST_FAILED = "LEADERBOARD_REQUEST_FAILED";


export const USER_RECENT_QUIZ_REQUEST = "USER_RECENT_QUIZ_REQUEST";
export const USER_RECENT_QUIZ_SUCCESS = "USER_RECENT_QUIZ_SUCCESS";
export const USER_RECENT_QUIZ_FAILED = "USER_RECENT_QUIZ_FAILED";
export const SET_USER_NULL = "SET_USER_NULL";