export const LEADERBOARD_REQUEST = "LEADERBOARD_REQUEST";
export const LEADERBOARD_REQUEST_SUCCESS = "LEADERBOARD_REQUEST_SUCCESS";
export const LEADERBOARD_REQUEST_FAILED = "LEADERBOARD_REQUEST_FAILED";


