export { Login } from "./Login"
export { Signup } from "./Signup"
export { Home } from "./Home"
export { Loading } from "./Loading"
export { LeaderBoard } from "./LeaderBoard"
export { Quiz } from "./Quiz"
export * from "./Terms"
export * from "./Result"
export * from "./Profile"
export * from "./ProfilePage"